### ISSUE TITLE
HelloWord example fails to compile

### ISSUE THREAD

**Issue by Reedyuk** [neow3j/neow3j-boilerplate#3]
When running the command:
```
./gradlew neow3jCompile
```

Gradle fails with the following error:
```
A problem was found with the configuration of task ':neow3jCompile' (type 'Neow3jCompileTask').
  - In plugin 'io.neow3j.gradle-plugin' type 'io.neow3j.devpack.gradle.Neow3jCompileTask' property 'outputDir' has @Input annotation used on property of type 'RegularFileProperty'.
```

**Comment by gsmachado** [comment]
@Reedyuk oh... that's surprising.

Let me take a look at this.

BTW: what's your local Java version?

**Comment by Reedyuk** [comment]
OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)

Running on a M2 Macbook

Thanks for the quick reply

**Comment by gsmachado** [comment]
@Reedyuk I already found the issue. It was my mistake when I upgraded some days ago the Gradle Wrapper of the whole project. Sorry about this.

Fixed with https://github.com/neow3j/neow3j-boilerplate-contracts/pull/5 . Now everything should work fine. 😄 

Closing this one, now.

Join [AxLabs](https://axlabs.com) Discord server if would like to chat.
